# golangci-lint configuration for Waffle

run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - errcheck      # Check for unchecked errors
    - gosimple      # Simplify code
    - govet         # Vet examines Go source code
    - ineffassign   # Detect ineffectual assignments
    - staticcheck   # Static analysis
    - unused        # Check for unused code
    - gofmt         # Check formatting
    - goimports     # Check imports
    - misspell      # Check for misspelled words
    - revive        # Fast, configurable, extensible linter
    - gosec         # Security checks
    - gocritic      # Opinionated linter
    - bodyclose     # Check HTTP response body is closed
    - noctx         # Check for sending HTTP requests without context
    - unparam       # Check for unused function parameters
    - unconvert     # Remove unnecessary type conversions
    - prealloc      # Find slice declarations that could be preallocated
    - exportloopref # Check for pointers to loop variables
    - errorlint     # Find code that will cause problems with Go 1.13+ error wrapping

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
    
  govet:
    check-shadowing: true
    enable-all: true
    
  gofmt:
    simplify: true
    
  goimports:
    local-prefixes: github.com/waffle/waffle
    
  misspell:
    locale: US
    
  revive:
    confidence: 0.8
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
      - name: if-return
      - name: increment-decrement
      - name: var-naming
      - name: var-declaration
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf
      - name: empty-block
      - name: superfluous-else
      - name: unused-parameter
      - name: unreachable-code
      - name: redefines-builtin-id
      
  gosec:
    excludes:
      - G104  # Audit errors not checked (covered by errcheck)
      - G304  # File path provided as taint input (we need to read user files)
      
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
    disabled-checks:
      - unnamedResult
      - hugeParam
      
  staticcheck:
    checks: ["all"]

issues:
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gosec
        - errcheck
        - gocritic
        
    # Exclude property test files from certain checks
    - path: properties_test\.go
      linters:
        - gosec
        - errcheck
        
  max-issues-per-linter: 0
  max-same-issues: 0
  
  # Show all issues
  exclude-use-default: false

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true
